### ISSUE TITLE
Windows "Skipping  blah.caf for search because of archive bit"  if bit is on or off?

### ISSUE THREAD

**Issue by dwids** [binsento42/Cathy#2]
Hello. Thanks for the code. I've got hundreds of .caf files and am looking for ways to re-use/export them. I'm on Windows and have a basic understating of Python.

I have unset the attribute bit from 2 of my 3 sample .caf files (it was set) but am still getting errors:
```
C:\temp\testing\Cathy_python>attrib *.caf
                     C:\temp\testing\Cathy_python\AudioBooks_01.caf
                     C:\temp\testing\Cathy_python\AUDIOBOOKS_02.caf
A                    C:\temp\testing\Cathy_python\TV_001.caf

C:\temp\testing\Cathy_python>python Cathy.py search "kuwait"
Skipping AudioBooks_01.caf for search because of archive bit
Skipping AUDIOBOOKS_02.caf for search because of archive bit
Skipping TV_001.caf for search because of archive bit

C:\temp\testing\Cathy_python>
```

Thank you

**Comment by binsento42** [comment]
Glad my code can be of use to someone. The archive bit the error is referring to is the archive flag that you can set (or will be set!?) in the original Cathy GUI. As I said in the introduction: "I'm not sure what the original Cathy implementation for the archive flag is, but in this python version archive disks are skipped by search". I've never had Cathy set the archive bit for one of my caf files, and it appears you can't set it manually in the original. But then, I've only used HDs and maybe the archive bit sets for optical storage!? 

I'm now using this flag to distiguish between regular storage and backup HDs, so that search doesn't look in the backups to speed things up. If you don't like this behaviour you can set the search to also include caf files with the archive flag set by changing line 569 to:

			searchFor(pth,argv[2], archive=True)

Maybe I should've added a cli command for this, but I thought it would be easy enough to change this in the script if necessary. The error message you are referring to is thrown in line 542 and 543. The 'flask GUI' version does have the option to include the archive cafs in search or even search individual disks.

Before starting the current implementation I pondered about a generic export (preferably xml), but couldn't think of a useful structured way to do this, so I haven't pursued this any further, but I'm open to suggestions. The original Cathy does have an option to export the directory tree in text format I think. The python search is very basic and doesn't do wildcards, so it's not very useful for export.

**Comment by dwids** [comment]
Aha, thank you.  Your suggestion about Optical Storage defaulting to archive=1 seems to be correct. The very good "CathyGuide-Eng.pdf" says as much, as I've just read:

`The Archive box was automatically ticked because this is a CD.`

This is during the Catalog operation on the disk.  

I thought I'd look at my _existing_ CD/DVD .caf files in the Catalog view. A quick test in the original GUI suggests you cannot bulk-toggle this bit, even though it appears to let you do it.  

I'll try the code change and see how that goes.

I contacted Robert some years ago.  I was looking for a way to export chosen Columns to, say, a CSV or Tab-delimited text file; with the ultimate objective of importing into a (yet unknown) open source DB catalogue system. He was kind enough to reply but told me of the "dir /s" output that his 'bulk' (fullist) save produced. I spent  ages trying to read that listing and convert it to a CSV. Got it basically working, but never properly.

**Comment by binsento42** [comment]
It took me quite some effort to understand the caf format, but once figured out it's pretty straightforward to create some sort of csv export. I could add that.

**Comment by dwids** [comment]
Hello again.  If you could add a csv/tab_del export (tab seems to work better with Excel import) that would be brilliant.  It would actually negate the need for me to use your Python CLI.  

If I couldn't get the Cathy data into a DB, then my fallback option would be a script that searches my 3 (three!) indexing/archiving systems: 

1. Cathy (ancient archives)
2. Everything ('live' indexing of the PC's drives)
3. Locate (my NAS)

...in one hit.

Either way, I did have a hiccup yesterday which may be of interest. I made the code change:

`searchFor(pth,argv[2], archive=True)`

And ran it against my 2 existing .caf files.  The Original GUI returns DOC_001 for a search of _Egypt_

I tried a few tests, but it kept returning the list of my 2 .caf files:

```
C:\temp\testing\Cathy_python>python cathy.py search Egypt
DOC_001.caf
TV_001.caf

C:\temp\testing\Cathy_python>python cathy.py search "Egypt"
DOC_001.caf
TV_001.caf

C:\temp\testing\Cathy_python>python cathy.py search juagkalfjsiskfk
DOC_001.caf
TV_001.caf
```
TV_001 has no references to Egypt and does not appear in the original GUI search for _Egypt_

**Comment by binsento42** [comment]
The listing of the caf files you are referring to is only to show progress in which files are processed and which are skipped, since the search can take pretty long and you don't want to the script to appear in a hangup. If a file is found with the search term in the filename the CLI says: 

Match: 'path-to-file-that-matches-search'

If you are sure that there is a file on DOC_001.caf that has 'egypt' in its filename there is no reason it wouldn't be found. My hypothesis would therefore be the caf files are not read at all because of version problems and the script disqualifies the caf file at line 115 or 121. You could ad print statement at line 123 to check if the script accepts your caf file as legal. I have only had caf files of the latest type/version so I had no means to test backward compatibility. In earlier versions there was some debug prints here but I dropped them. I should add some error messages here.

**Comment by binsento42** [comment]
Closing this issue because the original archive issue is resolved.
