### ISSUE TITLE
"Error in Parenting.Error in Parenting.Error in Parenting.Error in Parenting.Error in Parenting.Error in Parenting.Error in Parenting.

### ISSUE THREAD

**Issue by jimlynnjulian** [binsento42/Cathy#5]
The cathy.py file export option returns a file zero bytes in size. The cli window runs a continuing stream of "Error in Parenting" messages.

Windows 11 Pro, x64
Python 3.8.10

**Comment by sweco-sekrsv** [comment]
I have the same problem and the same error. I have attached an example. Example is exported with CathyCmd2314

Windows 10 Enterprise
Python 3.6.8
[test_export.zip](https://github.com/binsento42/Cathy/files/8221228/test_export.zip)

**Comment by binsento42** [comment]
I have never used CathyCmd and apparently I never ever updated my Cathy.exe so cathy.py only supported caf format 7 (but I had removed the warning so it would accept v8 files without warning). It took some hard byte level file compares and reverse engineering to figure out what had changed between v7 and v8 and I concluded a short has changed to a long to accomodate for larger volumes (more files/directories). It now seems to work with your test_export.zip and is backwards compatible but isn't thoroughly tested since I only had 1 v8 file to test with, so the assumption for now is that this long/short conversion is the only difference between v7 and v8. Please test some more and confirm this issue can be closed.

**Comment by jimlynnjulian** [comment]
Seems to be working now.
One question: Cathy replaces foreign characters with question marks. What does your program do?
Go ahead and close this issue.
Thanks.

**Comment by jimlynnjulian** [comment]
Hate to be the bearer of bad news, but I started an export several hours ago and the script is still running. The caf file is 18MB and the CSV files is, currently, 45MB in size. I haven't opened the file yet. I did run a previous conversion and the CAF file was 30KB and the CSV was 40KB. I suspect there is something in one of the fields that may have thrown the script off.
I'll examine both conversions and report the results back.
The problem turned out to be documents, especially HTML files. Every css, gif, html, etc file is scanned and converted.
These trivial accessories can number in the thousands.
All drives with nothing but major media turned out well. 
Drives with records and documents could take, literally, days to convert, if not weeks.

**Comment by binsento42** [comment]
The export file is far less efficient as the caf file, since for each filename also full path is exported. Depending on the depth of directories this can turn out a lot larger and the algoritm to create the full paths needs a lot of searches. Cathy only keeps track of a parent directory of a file and as such has a very efficient file size, but such an export would not be very useful i.e. be a terrible puzzle to put back together. I never use the export and only implemented it as a request and it is intended for putting caf files in another database. My thought was that if you put it in a database and search for a file you'd want to know where it is located, hence the full path.
