### ISSUE TITLE
 Support for foreign characters?

### ISSUE THREAD

**Issue by sweco-sekrsv** [binsento42/Cathy#6]
Hi!

Searching and exporting for files that use foreign characters such as åäö ÅÄÖ does not work. Would it be possible to add it?
See my attached example. The txt file have been exported from the Cathy.exe gui and it looks correct.

However using you brilliant script as you can see, the foreign characters ends up missing. For example searching for "test" we get two matches:
[\work\cathy\folder_test_foreign]\mapp \test .txt,0
[\work\cathy\folder_test_foreign]\mapp \test .txt,0
We lack the foreign characters, they have been removed. The results should really be:
[\work\cathy\folder_test_foreign]\mapp å\test Ä.txt,0
[\work\cathy\folder_test_foreign]\mapp Ö\test Å.txt,0

If I search for "test Ä" no results show, it should show one result.
[foreign_characters.zip](https://github.com/binsento42/Cathy/files/9014741/foreign_characters.zip)

**Comment by binsento42** [comment]
Character encoding in python is always a hassle, so I didn't put much effort in since I don't care for it much. I think changing line 404 from `chain += chr.decode()` to `chain += chr.decode('unicode_escape')` seems to fix this (or at least mostly). Due to some technical challenges at home I can't push a bugfix in the repository right now. If the fix works let me know so I can keep it for a new release.

Since the string handling of python2 is completely different from python3 some more changes are needed to get this also working on python2. At line 595 add:
```
if version_info[0] == 2:
    term = term.decode('utf-8').lower()
```

**Comment by binsento42** [comment]
A new version with the proposed fixes has been committed. Since I haven't had any feedback on the fixes and they appear to be working for me I'm closing this issue.
